# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://mezze-tech-bot.herokuapp.com/v2/entry/near-mezze/mezze-tech-tutorials/main/comments

repository: "near-mezze/mezze-tech-tutorials"
comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "main"

search: true